lib/yolo_web/router.ex
defmodule YoloWeb.Router do
  use YoloWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", YoloWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/uploads", UploadController, only: [:new, :create]
    get "/webcam", WebcamController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", YoloWeb do
  #   pipe_through :api
  # end
end

lib/yolo/application.ex
defmodule Yolo.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the endpoint when the application starts
      YoloWeb.Endpoint,
      # Starts a worker by calling: Yolo.Worker.start_link(arg)
      {Yolo.Worker, [name: Yolo.Worker]},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Yolo.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    YoloWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/yolo/worker.ex
defmodule Yolo.Worker do
  use GenServer

  @timeout 5_000
  @uuid4_size 16

  def start_link(opts \\ []) do
    GenServer.start_link(__MODULE__, :ok, opts)
  end

  @default_config [
    python: "python", 
    detect_script: "python_scripts/detect.py",
    model: "yolov3"
  ]
  
def config do
  @default_config
  |> Keyword.merge(Application.get_env(:yolo, __MODULE__, []))
  
  #loads the values from env variables when {:system, env_var_name}
  |> Enum.map(fn 
    
    # it finds the full path when not provided
    {:python, path} -> {:python, System.find_executable(path)}

    # it loads the value from the environment variable
    # when the env variable is not set, it defaults to @default_config[option]
    {option, {:system, env_variable}} -> 
      {option, System.get_env(env_variable, @default_config[option])}
    
    # all the other options
    config -> config
  
  end)
  |> Enum.into(%{})
end

  def init(:ok) do
    config = config()
    
    port = Port.open(
      {:spawn_executable, config.python}, 
      [:binary, :nouse_stdio, {:packet, 4}, 
      args: [config.detect_script, config.model]
    ])

    {:ok, %{port: port, requests: %{}}}
  end


  def request_detection(pid, image) do
    # UUID.uuid4(:hex) is 32 bytes
    image_id = UUID.uuid4() |> UUID.string_to_binary!()
    request_detection(pid, image_id, image)
  end


  def request_detection(pid, image_id, image) when byte_size(image_id) == @uuid4_size do
    GenServer.call(pid, {:detect, image_id, image})
  end

  def await(image_id, timeout \\ @timeout) do
    receive do
      {:detected, ^image_id, result} -> result
    after
      timeout -> {:detection_timeout, image_id}
    end
  end

  def handle_call({:detect, image_id, image_data}, {from_pid, _}, worker) do
    Port.command(worker.port, [image_id, image_data])
    worker = put_in(worker, [:requests, image_id], from_pid)
    {:reply, image_id, worker}
  end


  def handle_info({port, {:data, <<image_id::binary-size(@uuid4_size), json_string::binary()>>}}, %{port: port}=worker) do
    result = get_result!(json_string)
    # getting from pid and removing the request from the map
    {from_pid, worker} = pop_in(worker, [:requests, image_id])
    # sending the result map to from_pid
    send(from_pid, {:detected, image_id, result})
    {:noreply, worker}
  end


  defp get_result!(json_string) do
    result = Jason.decode!(json_string)
    %{
      shape: %{width: result["shape"]["width"], height: result["shape"]["height"]},
      objects: get_objects(result["labels"], result["boxes"])
    }
  end

  def get_objects(labels, boxes) do
    Enum.zip(labels, boxes)
    |> Enum.map(fn {label, [x, y, bottom_right_x, bottom_right_y]}->
      w = bottom_right_x - x
      h = bottom_right_y - y
      %{label: label, x: x, y: y, w: w, h: h}
    end)
  end
end

lib/yolo_web/controllers/page_controller.ex
defmodule YoloWeb.PageController do
  use YoloWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/yolo_web/controllers/upload_controller.ex
defmodule YoloWeb.UploadController do
  use YoloWeb, :controller

  def new(conn, _params) do
    render(conn, "new.html")
  end

  def create(conn, %{"upload" => upload}=_params) do
    data = File.read!(upload.path)
    detection = Yolo.Worker.request_detection(Yolo.Worker, data) |> Yolo.Worker.await()

    base64_image = base64_inline_image(data, upload.content_type)
    render(conn, "show.html", image: base64_image, detection: detection)
  end

  defp base64_inline_image(data, content_type) do
    image64 = Base.encode64(data)
    "data:#{content_type};base64, #{image64}"
  end
end

lib/yolo_web/controllers/webcam_controller.ex
defmodule YoloWeb.WebcamController do
  use YoloWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end

end

lib/yolo_web/views/error_view.ex
defmodule YoloWeb.ErrorView do
  use YoloWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/yolo_web/views/layout_view.ex
defmodule YoloWeb.LayoutView do
  use YoloWeb, :view
end

lib/yolo_web/views/page_view.ex
defmodule YoloWeb.PageView do
  use YoloWeb, :view
end

lib/yolo_web/views/upload_view.ex
defmodule YoloWeb.UploadView do
  use YoloWeb, :view
end

lib/yolo_web/views/webcam_view.ex
defmodule YoloWeb.WebcamView do
  use YoloWeb, :view
end

lib/yolo_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Yolo · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
          </ul>
        </nav>
        <a href="http://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/yolo_web/templates/page/index.html.eex
<section class="row">
  <article class="column">
    <h2>Examples</h2>
    <ul>
      <li>
        <a href="<%= Routes.upload_path(@conn, :new) %>">Detect Objects in an Uploaded Image</a>
      </li>
      <li>
        <a href="<%= Routes.webcam_path(@conn, :index) %>">Real-time Webcam Object Detection</a>
      </li>
    </ul>
  </article>
</section>

lib/yolo_web/templates/upload/new.html.eex
<%= form_for @conn, Routes.upload_path(@conn, :create), [multipart: true], fn f-> %>
    <%= file_input f, :upload, class: "form-control" %>
    <%= submit "Detect", class: "button"%>
<% end %>

lib/yolo_web/templates/upload/show.html.eex
<a class="button button-outline" href="/uploads/new">New Image</a>

<svg width="<%= @detection.shape.width %>" height="<%= @detection.shape.height %>">
  <g fill="grey" transform="scale(0.5 0.5)">
    <image width="<%= @detection.shape.width %>" height="<%= @detection.shape.height %>" xlink:href="<%= @image %>"></image>
    <%= for o <- @detection.objects do %>
      <rect x="<%= o.x - 2%>" y="<%= o.y - 20%>" height="20" width="100" fill="blue"/>
      <text x="<%= o.x %>" y="<%= o.y %>" dy="-5" font-family="sans-serif" font-size="16px" font-weight="bold" fill="white"><%= o.label %></text>
      <rect x="<%= o.x %>" y="<%= o.y %>" width="<%= o.w %>" height="<%= o.h %>" style="fill:rgb(0,0,0,0);stroke-width:3;stroke:rgb(0,0,255)" /> 
    <% end %>
  </g>
</svg>

lib/yolo_web/templates/webcam/index.html.eex
<button id="start_stop">Start</button>
<div class="camera-container scaled-camera">
    <div id="camera"></div>
    <canvas id="objects" width="1280" height="720"></canvas>
</div>